export enum DeviceVariant{
    AIR_CONDITIONING = 'AIR CONDITIONING',
    WASHING_MACHINE = 'WASHING MACHINE',
    TH_SENSOR = 'TH SENSOR',
    LAMP = 'LAMP',
    GATE = 'GATE',
    SPRINKLER = 'SPRINKLER',
    SOLAR_PANELS = 'SOLAR PANELS',
    HOME_BATTERY = 'HOME BATTERY',
    CAR_CHARGER = 'CAR CHARGER'

}