version: '3.7'
services:
  redis:
    image: redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:latest
    ports:
      - "84:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./images:/usr/share/nginx/html/images
      - ../smart-home-client/build:/usr/share/nginx/html

volumes:
  redis_data:
  nginx_images: